//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public System.DateTime Request_Date { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Status { get; set; }
        public int User_Id { get; set; }
        public int Document_Id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
